# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f1f61a2a9c944302f73491592144d9bce0b5721e9e15e86f811b92db289e2a0f8dd229ee0768b32da4a7e59d9ce487cfee5e5885bde6017fc0e8db7d758c987

test:
  secret_key_base: 65c2da49de13ea6c7693310d7c85f921d349a138eb0e6f3bb6ad11a6473f3e4deba22f3d6a1893444067d9b73eb3f0660073f26270f7ab224c330c6fb5b15da1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
